insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('Ninguno', '', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('gramos', 'g', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('kilogramos', 'kg', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('litros', 'lt', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('centímetros', 'cm', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('kilogramo por centímetro cuadrado', 'kg/cm²', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('litros por descarga', 'lpd', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('presión del agua', 'PSI', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('pulgadas', '"', current_timestamp);
insert into tbl_magnitud(unidad, simbolo, fecha_registro) values('tamaño nominal de la tubería', '" NPS', current_timestamp);
insert into tbl_caracteristica(atributo, magnitud_id, atributo2, magnitud2_id, atributo3, magnitud3_id, atributo4, magnitud4_id, atributo5, magnitud5_id, atributo6, magnitud6_id, atributo7, magnitud7_id, atributo8, magnitud8_id, atributo9, magnitud9_id, atributo10, magnitud10_id, fecha_registro) values('Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, current_timestamp);
insert into tbl_caracteristica(atributo, magnitud_id, atributo2, magnitud2_id, atributo3, magnitud3_id, atributo4, magnitud4_id, atributo5, magnitud5_id, atributo6, magnitud6_id, atributo7, magnitud7_id, atributo8, magnitud8_id, atributo9, magnitud9_id, atributo10, magnitud10_id, fecha_registro) values('Descarga', 7, 'Largo', 5, 'Linea', 1, 'Incluye asiento', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, 'Ninguno', 1, current_timestamp);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Hogar', 'hogar', 'categoria/hogar.png', current_timestamp, 1, 0, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Grifería', 'grifería', 'categoria/griferia.png', current_timestamp, 1, 0, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Plomería', 'plomería', 'categoria/plomeria.png', current_timestamp, 1, 0, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Pisos y recubrimientos', 'pisos-y-recubrimientos', 'categoria/pisos-y-recubrimientos.png', current_timestamp, 1, 0, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Promociones', 'promociones', 'categoria/promociones.png', current_timestamp, 1, 0, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Compra por Marca', 'compra-por-marca', 'categoria/compra-por-marca.png', current_timestamp, 1, 0, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Baño', 'baño', '', current_timestamp, 2, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Cocina', 'cocina', '', current_timestamp, 2, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Cuarto de lavado', 'cuarto-de-lavado', '', current_timestamp, 2, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Pisos y azulejos', 'pisos-y-azulejos', '', current_timestamp, 2, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Patio y jardín', 'patio-y-jardín', '', current_timestamp, 2, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Mantenimiento del hogar', 'mantenimiento-del-hogar', '', current_timestamp, 2, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Accesorios para baño', 'accesorios-para-baño', '', current_timestamp, 2, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Monomandos', 'monomandos', '', current_timestamp, 2, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Mezcladoras', 'mezcladoras', '', current_timestamp, 2, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Salida para tina', 'salida-para-tina', '', current_timestamp, 2, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Regaderas', 'regaderas', '', current_timestamp, 2, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Fluxómetros', 'fluxómetros', '', current_timestamp, 2, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Productos para Gas', 'productos-para-gas', '', current_timestamp, 2, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Productos para agua', 'productos-para-agua', '', current_timestamp, 2, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Bombas y equipos', 'bombas-y-equipos', '', current_timestamp, 2, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Tinacos y Tanques', 'tinacos-y-tanques', '', current_timestamp, 2, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Accesorios para tubería', 'accesorios-para-tubería', '', current_timestamp, 2, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Piso interior', 'piso-interior', '', current_timestamp, 2, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Piso exterior', 'piso-exterior', '', current_timestamp, 2, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Mallas y decorativos', 'mallas-y-decorativos', '', current_timestamp, 2, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Pegamentos y otros materiales', 'pegamentos-y-otros-materiales', '', current_timestamp, 2, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('WC/Sanitarios', 'wc-sanitarios', '', current_timestamp, 3, 1, 2);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Llaves', 'llaves', '', current_timestamp, 3, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Regadera', 'regadera', '', current_timestamp, 3, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Accesorios', 'accesorios', '', current_timestamp, 3, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Asientos', 'asientos', '', current_timestamp, 3, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Lavabos', 'lavabos', '', current_timestamp, 3, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Tinas', 'tinas', '', current_timestamp, 3, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Muebles para baño', 'muebles-para-baño', '', current_timestamp, 3, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Espejos', 'espejos', '', current_timestamp, 3, 1, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Llaves de cocina (monomandos/mezcladoras)', 'llaves-de-cocina-(monomandos-mezcladoras)', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Tarjas', 'tarjas', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Parrilla y campanas', 'parrilla-y-campanas', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Acabados', 'acabados', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Paquetes Tekaway', 'paquetes-tekaway', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Purificadores', 'purificadores', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Trituradores', 'trituradores', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Contracanastas', 'contracanastas', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Dispensador de jabón', 'dispensador-de-jabón', '', current_timestamp, 3, 2, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Calentadores', 'calentadores', '', current_timestamp, 3, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Refacciones de Calentadores', 'refacciones-de-calentadores', '', current_timestamp, 3, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Lavaderos', 'lavaderos', '', current_timestamp, 3, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Llaves para gas', 'llaves-para-gas', '', current_timestamp, 3, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Llaves para agua', 'llaves-para-agua', '', current_timestamp, 3, 3, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Pisos para exterior', 'pisos-para-exterior', '', current_timestamp, 3, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Pisos para interior', 'pisos-para-interior', '', current_timestamp, 3, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Recubrimientos', 'recubrimientos', '', current_timestamp, 3, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Pisos rectificados', 'pisos-rectificados', '', current_timestamp, 3, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Adhesivo y materiales para piso', 'adhesivo-y-materiales-para-piso', '', current_timestamp, 3, 4, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Albercas', 'albercas', '', current_timestamp, 3, 5, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Tinas de hidromasajes', 'tinas-de-hidromasajes', '', current_timestamp, 3, 5, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Complementos', 'complementos', '', current_timestamp, 3, 5, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Servicios de instalación', 'servicios-de-instalación', '', current_timestamp, 3, 6, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Adhesivos', 'adhesivos', '', current_timestamp, 3, 6, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Impermeabilizantes', 'impermeabilizantes', '', current_timestamp, 3, 6, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Ventilación', 'ventilación', '', current_timestamp, 3, 6, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Minisplit', 'minisplit', '', current_timestamp, 3, 6, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Ventiladores de techo', 'ventiladores-de-techo', '', current_timestamp, 3, 6, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Para baño', 'para-baño', '', current_timestamp, 3, 8, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Para cocina', 'para-cocina', '', current_timestamp, 3, 8, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Automáticos', 'automáticos', '', current_timestamp, 3, 8, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Para baño', 'para-baño', '', current_timestamp, 3, 9, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Para cocina', 'para-cocina', '', current_timestamp, 3, 9, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Mezcladora 4”', 'mezcladora-4”', '', current_timestamp, 3, 9, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Mezcladora 8”', 'mezcladora-8”', '', current_timestamp, 3, 9, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Regadera de teléfono', 'regadera-de-teléfono', '', current_timestamp, 3, 11, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Brazo para regadera', 'brazo-para-regadera', '', current_timestamp, 3, 11, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Plato ancho', 'plato-ancho', '', current_timestamp, 3, 11, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Gas usos generales', 'gas-usos-generales', '', current_timestamp, 3, 13, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Pig tail', 'pig-tail', '', current_timestamp, 3, 13, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Paquetes para instalación', 'paquetes-para-instalación', '', current_timestamp, 3, 13, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Llaves de control para Gas', 'llaves-de control-para-gas', '', current_timestamp, 3, 13, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Conexiones', 'conexiones', '', current_timestamp, 3, 13, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Uso comercial', 'uso-comercial', '', current_timestamp, 3, 13, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Válvulas', 'válvulas', '', current_timestamp, 3, 13, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Lavabo/Fregadero', 'lavabo-fregadero', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Sanitarios', 'sanitarios', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Llaves de control', 'llaves-de-control', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Lavadora', 'lavadora', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Mezcladoras', 'mezcladoras', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Monomandos', 'monomandos', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Paquetes para', 'paquetes-para', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Manguera de desagüe', 'manguera-de-desagüe', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Calentadores', 'calentadores', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Sanitarios', 'sanitarios', '', current_timestamp, 3, 14, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Bombas', 'bombas', '', current_timestamp, 3, 15, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Electrobombas', 'electrobombas', '', current_timestamp, 3, 15, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Equipo hidroneumático', 'equipo-hidroneumático', '', current_timestamp, 3, 15, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Presurizadora', 'presurizadora', '', current_timestamp, 3, 15, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Tinacos', 'tinacos', '', current_timestamp, 3, 16, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Tanque', 'tanque', '', current_timestamp, 3, 16, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Cisterna', 'cisterna', '', current_timestamp, 3, 16, 1);
insert into tbl_categoria(nombre, ceo, imagen, fecha_registro, nivel, nivel_padre, caracteristica_id) values('Tolva', 'tolva', '', current_timestamp, 3, 16, 1);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Ambiance', 'ambiance', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('American Standard', 'american-standard', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Bosch', 'bosch', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Calorex', 'calorex', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Cinsa', 'cinsa', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Coflex', 'coflex', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Corona', 'corona', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Daltile', 'daltile', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Dica', 'dica', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('EB Técnica', 'eb-técnica', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Fluidmaster', 'fluidmaster', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Gante', 'gante', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Helvex', 'helvex', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Hunter', 'hunter', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Intex', 'intex', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Los Ovalines', 'los-ovalines', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Mabe', 'mabe', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Moen', 'moen', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Niasa', 'niasa', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Pedrollo', 'pedrollo', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Plados', 'plados', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Porcelanite', 'porcelanite', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Proyecta', 'proyecta', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Rheem', 'rheem', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Rotoplas', 'rotoplas', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Teka', 'teka', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Tendenzza', 'tendenzza', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Tiber', 'tiber', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('Urrea', 'urrea', current_timestamp);
insert into tbl_marca(nombre, ceo, fecha_registro) values('White-Westinghouse', 'white-westinghouse', current_timestamp);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Ambiance', 'ambiance', 'marca/banner/ambiance-1.png', 1, current_timestamp, 1);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Ambiance 2', 'ambiance-2', 'marca/banner/ambiance-2.png', 2, current_timestamp, 1);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('American Standard', 'american-standard', 'marca/banner/american-standard-1.png', 1, current_timestamp, 2);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('American Standard 2', 'american-standard-2', 'marca/banner/american-standard-2.png', 2, current_timestamp, 2);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Bosch', 'bosch', 'marca/banner/bosch-1.png', 1, current_timestamp, 3);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Bosch 2', 'bosch-2', 'marca/banner/bosch-2.png', 2, current_timestamp, 3);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Calorex', 'calorex', 'marca/banner/calorex-1.png', 1, current_timestamp, 4);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Calorex 2', 'calorex-2', 'marca/banner/calorex-2.png', 2, current_timestamp, 4);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Cinsa', 'cinsa', 'marca/banner/cinsa-1.png', 1, current_timestamp, 5);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Cinsa 2', 'cinsa-2', 'marca/banner/cinsa-2.png', 2, current_timestamp, 5);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Coflex', 'coflex', 'marca/banner/coflex-1.png', 1, current_timestamp, 6);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Coflex 2', 'coflex-2', 'marca/banner/coflex-2.png', 2, current_timestamp, 6);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Corona', 'corona', 'marca/banner/corona-1.png', 1, current_timestamp, 7);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Corona 2', 'corona-2', 'marca/banner/corona-2.png', 2, current_timestamp, 7);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Daltile', 'daltile', 'marca/banner/daltile-1.png', 1, current_timestamp, 8);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Daltile 2', 'daltile-2', 'marca/banner/daltile-2.png', 2, current_timestamp, 8);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Dica', 'dica', 'marca/banner/dica-1.png', 1, current_timestamp, 9);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Dica 2', 'dica-2', 'marca/banner/dica-2.png', 2, current_timestamp, 9);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('EB Técnica', 'eb-técnica', 'marca/banner/eb-técnica-1.png', 1, current_timestamp, 10);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('EB Técnica 2', 'eb-técnica-2', 'marca/banner/eb-técnica-2.png', 2, current_timestamp, 10);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Fluidmaster', 'fluidmaster', 'marca/banner/fluidmaster-1.png', 1, current_timestamp, 11);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Fluidmaster 2', 'fluidmaster-2', 'marca/banner/fluidmaster-2.png', 2, current_timestamp, 11);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Gante', 'gante', 'marca/banner/gante-1.png', 1, current_timestamp, 12);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Gante 2', 'gante-2', 'marca/banner/gante-2.png', 2, current_timestamp, 12);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Helvex', 'helvex', 'marca/banner/helvex-1.png', 1, current_timestamp, 13);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Helvex 2', 'helvex-2', 'marca/banner/helvex-2.png', 2, current_timestamp, 13);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Hunter', 'hunter', 'marca/banner/hunter-1.png', 1, current_timestamp, 14);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Hunter 2', 'hunter-2', 'marca/banner/hunter-2.png', 2, current_timestamp, 14);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Intex', 'intex', 'marca/banner/intex-1.png', 1, current_timestamp, 15);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Intex 2', 'intex-2', 'marca/banner/intex-2.png', 2, current_timestamp, 15);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Los Ovalines', 'los-ovalines', 'marca/banner/los-ovalines-1.png', 1, current_timestamp, 16);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Los Ovalines 2', 'los-ovalines-2', 'marca/banner/los-ovalines-2.png', 2, current_timestamp, 16);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Mabe', 'mabe', 'marca/banner/mabe-1.png', 1, current_timestamp, 17);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Mabe 2', 'mabe-2', 'marca/banner/mabe-2.png', 2, current_timestamp, 17);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Moen', 'moen', 'marca/banner/moen-1.png', 1, current_timestamp, 18);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Moen 2', 'moen-2', 'marca/banner/moen-2.png', 2, current_timestamp, 18);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Niasa', 'niasa', 'marca/banner/niasa-1.png', 1, current_timestamp, 19);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Niasa 2', 'niasa-2', 'marca/banner/niasa-2.png', 2, current_timestamp, 19);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Pedrollo', 'pedrollo', 'marca/banner/pedrollo-1.png', 1, current_timestamp, 20);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Pedrollo 2', 'pedrollo-2', 'marca/banner/pedrollo-2.png', 2, current_timestamp, 20);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Plados', 'plados', 'marca/banner/plados-1.png', 1, current_timestamp, 21);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Plados 2', 'plados-2', 'marca/banner/plados-2.png', 2, current_timestamp, 21);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Porcelanite', 'porcelanite', 'marca/banner/porcelanite-1.png', 1, current_timestamp, 22);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Porcelanite 2', 'porcelanite-2', 'marca/banner/porcelanite-2.png', 2, current_timestamp, 22);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Proyecta', 'proyecta', 'marca/banner/proyecta-1.png', 1, current_timestamp, 23);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Proyecta 2', 'proyecta-2', 'marca/banner/proyecta-2.png', 2, current_timestamp, 23);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Rheem', 'rheem', 'marca/banner/rheem-1.png', 1, current_timestamp, 24);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Rheem 2', 'rheem-2', 'marca/banner/rheem-2.png', 2, current_timestamp, 24);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Rotoplas', 'rotoplas', 'marca/banner/rotoplas-1.png', 1, current_timestamp, 25);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Rotoplas 2', 'rotoplas-2', 'marca/banner/rotoplas-2.png', 2, current_timestamp, 25);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Teka', 'teka', 'marca/banner/teka-1.png', 1, current_timestamp, 26);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Teka 2', 'teka-2', 'marca/banner/teka-2.png', 2, current_timestamp, 26);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Tendenzza', 'tendenzza', 'marca/banner/tendenzza-1.png', 1, current_timestamp, 27);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Tendenzza 2', 'tendenzza-2', 'marca/banner/tendenzza-2.png', 2, current_timestamp, 27);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Tiber', 'tiber', 'marca/banner/tiber-1.png', 1, current_timestamp, 28);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Tiber 2', 'tiber-2', 'marca/banner/tiber-2.png', 2, current_timestamp, 28);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Urrea', 'urrea', 'marca/banner/urrea-1.png', 1, current_timestamp, 29);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('Urrea 2', 'urrea-2', 'marca/banner/urrea-2.png', 2, current_timestamp, 29);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('White-Westinghouse', 'white-westinghouse', 'marca/banner/white-westinghouse-1.png', 1, current_timestamp, 30);
insert into tbl_marca_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id) values('White-Westinghouse 2', 'white-westinghouse-2', 'marca/banner/white-westinghouse-2.png', 2, current_timestamp, 30);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Sanitarios', 'ambiance', 'marca/categoria/ambiance-1.png', 1, current_timestamp, 1, 91);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Sanitarios One Piece', 'sanitarios-one-piece', 'marca/categoria/ambiance-2.png', 2, current_timestamp, 1, 83);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Lavabos', 'lavabos', 'marca/categoria/ambiance-3.png', 3, current_timestamp, 1, 33);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Sanitarios dos piezas', 'sanitarios-dos-piezas', 'marca/categoria/ambiance-4.png', 4, current_timestamp, 1, 83);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Sanitarios Inteligentes', 'sanitarios-inteligentes', 'marca/categoria/ambiance-5.png', 5, current_timestamp, 1, 83);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Sanitarios', 'sanitarios', 'marca/categoria/american-standard-1.png', 1, current_timestamp, 2, 83);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Mingitorios', 'mingitorios', 'marca/categoria/american-standard-2.png', 2, current_timestamp, 2, 83);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Mezcladoras', 'mezcladoras', 'marca/categoria/american-standard-3.png', 3, current_timestamp, 2, 86);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Lavabos', 'lavabos', 'marca/categoria/american-standard-4.png', 4, current_timestamp, 2, 33);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Monomandos', 'monomandos', 'marca/categoria/american-standard-5.png', 5, current_timestamp, 2, 87);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Tarjas', 'tarjas', 'marca/categoria/american-standard-6.png', 6, current_timestamp, 2, 38);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Calentadores gas LP', 'calentadores-gas-lp', 'marca/categoria/bosch-1.png', 1, current_timestamp, 3, 47);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Calentadores eléctricos', 'calentadores-eléctricos', 'marca/categoria/bosch-2.png', 2, current_timestamp, 3, 46);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Calentadores de depósito', 'calentadores-de-depósito', 'marca/categoria/calorex-1.png', 1, current_timestamp, 4, 90);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Calentadores de paso', 'calentadores-de-paso', 'marca/categoria/calorex-2.png', 2, current_timestamp, 4, 47);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Calentadores eléctricos', 'calentadores-eléctricos', 'marca/categoria/calorex-3.png', 3, current_timestamp, 4, 46);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Calentadores de depósito', 'calentadores-de-depósito', 'marca/categoria/cinsa-1.png', 1, current_timestamp, 5, 90);
insert into tbl_marcacategoria_imagen(nombre, ceo, imagen, orden, fecha_registro, marca_id, categoria_id) values('Calentadores de paso', 'calentadores-de-paso', 'marca/categoria/cinsa-2.png', 2, current_timestamp, 5, 47);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('Ninguno', current_timestamp, 1);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('58455022', current_timestamp, 29);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('200401001', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('8529021', current_timestamp, 1);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo1-5', current_timestamp, 1);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo1-6', current_timestamp, 1);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo1-7', current_timestamp, 1);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo1-8', current_timestamp, 1);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo1-9', current_timestamp, 1);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo1-10', current_timestamp, 1);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-1', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-2', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-3', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-4', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-5', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-6', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-7', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-8', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-9', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo2-10', current_timestamp, 2);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-1', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-2', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-3', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-4', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-5', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-6', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-7', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-8', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-9', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo3-10', current_timestamp, 3);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-1', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-2', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-3', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-4', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-5', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-6', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-7', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-8', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-9', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo4-10', current_timestamp, 4);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-1', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-2', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-3', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-4', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-5', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-6', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-7', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-8', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-9', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo5-10', current_timestamp, 5);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-1', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-2', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-3', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-4', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-5', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-6', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-7', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-8', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-9', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo6-10', current_timestamp, 6);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-1', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-2', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-3', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-4', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-5', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-6', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-7', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-8', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-9', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo7-10', current_timestamp, 7);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-1', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-2', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-3', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-4', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-5', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-6', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-7', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-8', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-9', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo8-10', current_timestamp, 8);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-1', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-2', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-3', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-4', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-5', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-6', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-7', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-8', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-9', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo9-10', current_timestamp, 9);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-1', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-2', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-3', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-4', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-5', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-6', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-7', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-8', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-9', current_timestamp, 10);
insert into tbl_modelo(nombre, fecha_registro, marca_id) values('modelo10-10', current_timestamp, 10);
insert into tbl_material(nombre, ceo, fecha_registro) values('Ninguno', '', current_timestamp);
insert into tbl_material(nombre, ceo, fecha_registro) values('Cerámica esmaltada', 'cerámica-esmaltada', current_timestamp);
insert into tbl_material(nombre, ceo, fecha_registro) values('Porcelana vítrea', 'porcelana-vítrea', current_timestamp);
insert into tbl_material(nombre, ceo, fecha_registro) values('Porcelana sanitaria', 'porcelana-sanitaria', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Ninguno', 'sin-color', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Negro', 'negro', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Azul', 'azul', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Marrón', 'marrón', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Gris', 'gris', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Verde', 'verde', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Naranja', 'naranja', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Rosa', 'rosa', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Púrpura', 'púrpura', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Rojo', 'rojo', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Blanco', 'blanco ', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Amarillo', 'amarillo', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Turquesa', 'turquesa', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Verde oliva', 'verde-oliva', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Verde menta', 'verde-menta', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Borgoña', 'borgoña', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Lavanda', 'lavanda', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Magenta', 'magenta', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Salmón', 'salmón', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Cian', 'cian', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Beige', 'beige', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Rosado', 'rosado', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Verde oscuro', 'verde-oscuro', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Verde oliva', 'verde-oliva', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Lila', 'lila', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Amarillo pálido', 'amarillo-pálido', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Fucsia', 'fucsia', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Mostaza', 'mostaza', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Ocre', 'ocre', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Trullo', 'trullo', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Malva', 'malva', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Púrpura oscuro', 'púrpura-oscuro', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Verde lima', 'verde-lima', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Verde claro', 'verde-claro', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Ciruela', 'ciruela', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Azul claro', 'azul-claro', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Melocotón', 'melocotón', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Violeta', 'violeta', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Tan', 'tan', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Granate', 'granate', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Café', 'café', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Plata', 'plata', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Gris', 'gris', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Beige', 'beige', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Acero inoxidable', 'acero-inoxidable', current_timestamp);
insert into tbl_color(nombre, ceo, fecha_registro) values('Cromo', 'cromo', current_timestamp);
insert into tbl_estilo(nombre, ceo, fecha_registro) values('Ninguno', '', current_timestamp);
insert into tbl_estilo(nombre, ceo, fecha_registro) values('Clásico', 'clásico', current_timestamp);
insert into tbl_acabado(nombre, ceo, fecha_registro) values('Ninguno', '', current_timestamp);
insert into tbl_acabado(nombre, ceo, fecha_registro) values('Brillante', 'brillante', current_timestamp);
insert into tbl_producto(nombre, ceo, descripcion, precio, peso, dimension, dimension2, dimension3, dimension4, dimension5, dimension6, dimension7, dimension8, dimension9, dimension10, sku, fecha_registro, categoria_id, marca_id, magnitud_id, modelo_id, material_id, color_id, estilo_id, acabado_id) values('Sanitario Andrómeda GS dos piezas blanco 4.8 L', 'sanitario-andrómeda-gs-dos-piezas-blanco-4-8-l', 'Realiza tu remodelación con este sanitario de dos piezas de alto brillo', 376.62, 0, '4.8', '', '', '', '', '', '', '', '', '', 'WC0001', current_timestamp, 28, 29, 1, 2, 2, 11, 2, 1);
insert into tbl_producto(nombre, ceo, descripcion, precio, peso, dimension, dimension2, dimension3, dimension4, dimension5, dimension6, dimension7, dimension8, dimension9, dimension10, sku, fecha_registro, categoria_id, marca_id, magnitud_id, modelo_id, material_id, color_id, estilo_id, acabado_id) values('Sanitario Aquapro dos piezas blanco ecoflush', 'sanitario-aquapro-dos-piezas-blanco-ecoflush', 'Sanitario Aquapro Corona, diseñado con una taza alargada, sistema de accionamiento dual tipo push, cuenta con tecnología EcoFlush, color blanco, consumo de agua promedio 3.8 lpf', 436.36, 0, '', '66.6', 'Aquapro', 'Sí', '', '', '', '', '', '', 'WC0002', current_timestamp, 28, 8, 1, 3, 3, 11, 1, 1);
insert into tbl_producto(nombre, ceo, descripcion, precio, peso, dimension, dimension2, dimension3, dimension4, dimension5, dimension6, dimension7, dimension8, dimension9, dimension10, sku, fecha_registro, categoria_id, marca_id, magnitud_id, modelo_id, material_id, color_id, estilo_id, acabado_id) values('Sanitario Aral one piece blanco', 'sanitario-aral-one-piece-blanco', 'Sanitario de una pieza Ambiance, estilo atemporal y confiado inspirado en el arte deco y los diseños arquitectónicos de renombre con detalles sofisticados que agregan fuerza y frescura', 1438.4, 55.7, 'Dual flush 6.0 lpf-4.2', '', '', 'Sí', '12.3 x 17.5', '20-80', 'Tecnología sifónica', '', '', '', 'WC0003', current_timestamp, 28, 2, 3, 4, 4, 11, 1, 2);
insert into tbl_producto_imagen(nombre, ceo, imagen, orden, fecha_registro, producto_id) values('Imagen 1', 'imagen-1', 'https://res.cloudinary.com/dftssxe9q/image/upload/v1712840734/r5rnfnvbahwgjs7uxutb.webp', 1, current_timestamp, 1);
insert into tbl_producto_imagen(nombre, ceo, imagen, orden, fecha_registro, producto_id) values('Imagen 2', 'imagen-2', 'https://res.cloudinary.com/dftssxe9q/image/upload/v1712841778/chsyt0hkbsludfhembmj.webp', 2, current_timestamp, 1);
insert into tbl_producto_imagen(nombre, ceo, imagen, orden, fecha_registro, producto_id) values('Imagen 3', 'imagen-3', 'https://res.cloudinary.com/dftssxe9q/image/upload/v1712841859/zggjkzj5vmq8i337uy4b.webp', 3, current_timestamp, 1);
insert into tbl_producto_imagen(nombre, ceo, imagen, orden, fecha_registro, producto_id) values('Imagen 1', 'imagen-1', 'https://res.cloudinary.com/dftssxe9q/image/upload/v1712841914/qpvshillrlwig7gfh95n.webp', 1, current_timestamp, 2);
insert into tbl_producto_imagen(nombre, ceo, imagen, orden, fecha_registro, producto_id) values('Imagen 1', 'imagen-1', 'https://res.cloudinary.com/dftssxe9q/image/upload/v1712841967/g4eik8kr1hbckzhcajwn.webp', 1, current_timestamp, 3);
insert into tbl_producto_imagen(nombre, ceo, imagen, orden, fecha_registro, producto_id) values('Imagen 2', 'imagen-2', 'https://res.cloudinary.com/dftssxe9q/image/upload/v1712842021/ruk8lowujbykweyspdhl.webp', 2, current_timestamp, 3);
insert into tbl_producto_imagen(nombre, ceo, imagen, orden, fecha_registro, producto_id) values('Imagen 3', 'imagen-3', 'https://res.cloudinary.com/dftssxe9q/image/upload/v1712842043/aggs6hpk4posm1vcx7q9.webp', 3, current_timestamp, 3);
insert into tbl_producto_imagen(nombre, ceo, imagen, orden, fecha_registro, producto_id) values('Imagen 4', 'imagen-4', 'https://res.cloudinary.com/dftssxe9q/image/upload/v1712842065/kfyfk3kkdmgqcngvcgqy.webp', 4, current_timestamp, 3);
insert into tbl_persona(nombre, apellido_paterno, apellido_materno, genero, fecha_nacimiento) values('Juan', 'Pérez', 'García', 'M', '1985-03-10');
insert into tbl_persona(nombre, apellido_paterno, apellido_materno, genero, fecha_nacimiento) values('María', 'Rodríguez', 'López', 'F', '1990-07-20');
insert into tbl_persona(nombre, apellido_paterno, apellido_materno, genero, fecha_nacimiento) values('Carlos', 'Sánchez', 'Martínez', 'M', '1988-11-05');
insert into tbl_persona(nombre, apellido_paterno, apellido_materno, genero, fecha_nacimiento) values('Laura', 'González', 'Ramírez', 'F', '1992-04-15');
insert into tbl_persona(nombre, apellido_paterno, apellido_materno, genero, fecha_nacimiento) values('Andrés', 'Fernández', 'Torres', 'M', '1983-09-25');
insert into tbl_persona(nombre, apellido_paterno, apellido_materno, genero, fecha_nacimiento) values('Ana', 'Morales', 'Vargas', 'F', '1987-12-08');
insert into tbl_persona(nombre, apellido_paterno, apellido_materno, genero, fecha_nacimiento) values('David', 'Jiménez', 'Herrera', 'M', '1995-06-30');
insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('admin', '', '','admi@gmail.com', 'pbkdf2_sha256$600000$6FYucAXVMQ1Ug9NHoLmiob$RUhRwKnIGKmrBXGFfWI6y2/3LtHmQvHm/BHuOV2GsTw=', true, true, true, current_timestamp);
insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('juan.perez', 'Juan', 'Pérez García','juan.perez@gmail.com', 'pbkdf2_sha256$600000$PdbpwaJYojwZqdU3e6Cexw$h0Xxj77tH6dJXuJCApEZgBUnfb7I+/5sOOVDldMsD/U=', false, false, true, current_timestamp);
insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('maria.rodriguez', 'María', 'Rodríguez López','maria.rodriguez@gmail.com', 'pbkdf2_sha256$600000$yNp91G8J4WbmmRgYOAqXZW$nbYF9TYW75/Db2hyySgabnEIFtl96SLObLsdiplbCw8=', false, false, true, current_timestamp);
insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('carlos.sanchez', 'Carlos', 'Sánchez Martínez','carlos.sanchez@gmail.com', 'pbkdf2_sha256$600000$3sFsUfGBJi5c6q4uzhzT54$uYhSIrpa7skk0yXyQkOguTTwG94w9MTlztL67oyGCa4=', false, false, true, current_timestamp);
insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('laura.gonzalez', 'Laura', 'González Ramírez','laura.gonzalez@gmail.com', 'pbkdf2_sha256$600000$4myDgEfVTc8gJjvFK6eV5H$DRnfLaVLtwWTUUrKv1Ry0yKLYxEPt4i/KHEdg+nhHQE=', false, false, true, current_timestamp);
insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('andres.fernandez', 'Andrés', 'Fernández Torres','andres.fernandez@gmail.com', 'pbkdf2_sha256$600000$vTlMTv61WtHBgGhD1FRHTG$6v/22AT1y9uKX8Fb2/zCnYeNJutGeOaKjni4pah3Trk=', false, false, true, current_timestamp);
insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('ana.morales', 'Ana', 'Morales Vargas','ana.morales@gmail.com', 'pbkdf2_sha256$600000$GjXAC98QVFu4UqqPpHZIj4$QrW5oP4r3ttX3A2g/qFpkWbagGQSioSFcLd33Q6N6Vc=', false, false, true, current_timestamp);
insert into auth_user(username, first_name, last_name, email, password, is_superuser, is_staff, is_active, date_joined) values('david.jimenez', 'David', 'Jiménez Herrera','david.jimenez@gmail.com', 'pbkdf2_sha256$600000$RmlqYtfMHLQz51Fne9tvak$cesyYCnbWV9CKuxIx2GvXvnPM713hmY9UYfWXMpV/OU=', false, false, true, current_timestamp);
insert into tbl_cliente(telefono, direccion, persona_id, usuario_id) values('+1 (555) 123-4567 123', 'Main St, Los Angeles, CA 90001', 1, 2);
insert into tbl_cliente(telefono, direccion, persona_id, usuario_id) values('+1 (555) 987-6543 456', 'Elm St, New York, NY 10002', 2, 3);
insert into tbl_cliente(telefono, direccion, persona_id, usuario_id) values('+1 (555) 234-5678 789', 'Oak Ave, Chicago, IL 60603', 3, 4);
insert into tbl_cliente(telefono, direccion, persona_id, usuario_id) values('+1 (555) 345-6789 101', 'Maple Rd, Miami, FL 33101', 4, 5);
insert into tbl_cliente(telefono, direccion, persona_id, usuario_id) values('+1 (555) 876-5432 222', 'Elm St, Los Angeles, CA 90002', 5, 6);
insert into tbl_cliente(telefono, direccion, persona_id, usuario_id) values('+1 (555) 765-4321 333', 'Oak Ave, New York, NY 10003', 6, 7);
insert into tbl_cliente(telefono, direccion, persona_id, usuario_id) values('+1 (555) 432-1098 444', 'Maple Rd, Chicago, IL 60604', 7, 8);
insert into tbl_orden(codigo, estado, precio_total, descuento, fecha_registro, cliente_id) values('PED0000001', 'P', 4879.38, 0, current_timestamp, 1);
insert into tbl_orden(codigo, estado, precio_total, descuento, fecha_registro, cliente_id) values('PED0000002', 'C', 3313.16, 0, current_timestamp, 2);
insert into tbl_orden(codigo, estado, precio_total, descuento, fecha_registro, cliente_id) values('PED0000003', 'P', 1438.40, 0, current_timestamp, 3);
insert into tbl_orden(codigo, estado, precio_total, descuento, fecha_registro, cliente_id) values('PED0000004', 'C', 5564.54, 0, current_timestamp, 4);
insert into tbl_orden(codigo, estado, precio_total, descuento, fecha_registro, cliente_id) values('PED0000005', 'P', 1249.34, 0, current_timestamp, 5);
insert into tbl_orden(codigo, estado, precio_total, descuento, fecha_registro, cliente_id) values('PED0000006', 'C', 1506.48, 0, current_timestamp, 6);
insert into tbl_orden(codigo, estado, precio_total, descuento, fecha_registro, cliente_id) values('PED0000007', 'P', 4502.76, 0, current_timestamp, 7);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(376.62, 3, 1129.86, current_timestamp, 1, 1);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(436.36, 2, 872.72, current_timestamp, 2, 1);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(1438.40, 2, 2876.80, current_timestamp, 3, 1);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(436.36, 1, 436.36, current_timestamp, 2, 2);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(1438.40, 2, 2876.80, current_timestamp, 3, 2);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(1438.40, 1, 1438.40, current_timestamp, 3, 3);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(376.62, 1, 376.62, current_timestamp, 1, 4);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(436.36, 2, 872.72, current_timestamp, 2, 4);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(1438.40, 3, 4315.20, current_timestamp, 3, 4);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(376.62, 1, 376.62, current_timestamp, 1, 5);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(436.36, 2, 872.72, current_timestamp, 2, 5);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(376.62, 4, 1506.48, current_timestamp, 1, 6);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(376.62, 2, 753.24, current_timestamp, 1, 7);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(436.36, 2, 872.72, current_timestamp, 2, 7);
insert into tbl_orden_detalle(precio, cantidad, subtotal, fecha_Registro, producto_id, orden_id) values(1438.40, 2, 2876.80, current_timestamp, 3, 7);

select * from public.tbl_magnitud order by id asc;
select * from public.tbl_caracteristica order by id asc;
select * from public.tbl_categoria order by id asc;
select * from public.tbl_marca order by id asc;
select * from public.tbl_marca_imagen order by id asc;
select * from public.tbl_marcacategoria_imagen order by id asc;
select * from public.tbl_modelo order by id asc;
select * from public.tbl_material order by id asc;
select * from public.tbl_color order by id asc;
select * from public.tbl_acabado order by id asc;
select * from public.tbl_estilo order by id asc;
select * from public.tbl_producto order by id asc;
select * from public.tbl_producto_imagen order by id asc;
select * from public.tbl_persona order by id asc;
select * from public.auth_user order by id asc;
select * from public.tbl_cliente order by id asc;
select * from public.tbl_orden order by id asc;
select * from public.tbl_orden_detalle order by id asc;